--------------------------------------------------------
--  File created - Sunday-April-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body P_COSTOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PROD"."P_COSTOS" AS
  -- ----------------------------------------------------------------------- --
  -- -20/11/2017.Modificacion:Se agrega seguimiento para el proceso nocturno.
  -- ----------------------------------------------------------------------- --
  /*********************Proceso que identifica si a un cliente se le adiministra el portafolio deceval**********************/
  PROCEDURE CLIENTE_ADMIN_DVAL (P_CLI_PER_NUM_IDEN VARCHAR2, P_CLI_PER_TID_CODIGO VARCHAR2, P_ADMINISTRA IN OUT VARCHAR2)  IS
  BEGIN
    SELECT CLI_ADM_PORTAFOLIO_DCVAL INTO P_ADMINISTRA
    FROM   CLIENTES
    WHERE  CLI_PER_NUM_IDEN   = P_CLI_PER_NUM_IDEN
    AND    CLI_PER_TID_CODIGO = P_CLI_PER_TID_CODIGO;  
  END;

  /*********************Proceso que identifica si un cliente es un APT o una CC******************************************/
  PROCEDURE CLIENTE_APT_CC (P_CLI_PER_NUM_IDEN VARCHAR2, P_APT_CC IN OUT VARCHAR2)  IS
    CURSOR C_ODP IS
      SELECT FON_CODIGO
      FROM   FONDOS
      WHERE  FON_CODIGO   = P_CLI_PER_NUM_IDEN;  

    R_ODP   C_ODP%ROWTYPE;

  BEGIN

    OPEN C_ODP;
    FETCH C_ODP INTO R_ODP;
    IF C_ODP%FOUND THEN
       P_APT_CC := 'S';
    ELSE
       P_APT_CC := 'N';
    END IF;

  END;

  /*********************Proceso que identifica si un titulo de una operación es físico o no***********************************/
  PROCEDURE TITULO_FISICO (LIC_BOL_MNEMONICO VARCHAR2, LIC_NUMERO_OPERACION NUMBER, LIC_NUMERO_FRACCION NUMBER, LIC_TIPO_OPERACION VARCHAR2, ES_TITULO_FISICO IN OUT NUMBER)  IS
  BEGIN
    SELECT COUNT(*) INTO ES_TITULO_FISICO
    FROM   TITULOS
    WHERE  ((LIC_TIPO_OPERACION = 'V' AND TLO_LIC_BOL_MNEMONICO_ES_VEN = LIC_BOL_MNEMONICO AND 
             TLO_LIC_NUMERO_OPERACION_ES_VE = LIC_NUMERO_OPERACION AND TLO_LIC_NUMERO_FRACCION_ES_VEN = LIC_NUMERO_FRACCION
             AND TLO_LIC_TIPO_OPERACION_ES_VEND = LIC_TIPO_OPERACION) OR
            (LIC_TIPO_OPERACION = 'C' AND TLO_BOL_MNEMONICO = LIC_BOL_MNEMONICO AND 
             TLO_LIC_NUMERO_OPERACION = LIC_NUMERO_OPERACION AND TLO_LIC_NUMERO_FRACCION = LIC_NUMERO_FRACCION
             AND TLO_LIC_TIPO_OPERACION = LIC_TIPO_OPERACION))
    AND    TLO_LTI_MNEMONICO = 'FI'
    AND    TLO_PORTAFOLIO    = 'S'
    AND    TLO_ETC_MNEMONICO IN ('DIS', 'GAR');
  END;

  /*********************Proceso que señala el valor de la tarifa del costo de acuerdo a los parametros señalados*************/
  PROCEDURE VALOR_TARIFA_COSTO (P_TIPO_TARIFA VARCHAR2, P_VALOR NUMBER, P_ANO NUMBER, P_COSTO IN OUT NUMBER)  IS 

  VALOR VARCHAR2(40);

  CURSOR C_ODP1 IS
      SELECT TSD_VALOR VALOR INTO VALOR
      FROM   TARIFAS_COSTOS_DECEVAL, TIPOS_TARIFAS_COSTOS
      WHERE  TSD_ANO = P_ANO
      AND    TSD_TTC_MNEMONICO = P_TIPO_TARIFA
      AND    TSD_TTC_MNEMONICO = TTC_MNEMONICO
      AND    ((TTC_RANGO = 'S' AND TSD_RANGO_INICIAL <= P_VALOR AND TSD_RANGO_FINAL >= P_VALOR)
      OR     (TTC_RANGO = 'N'));

    R_ODP1   C_ODP1%ROWTYPE;

  C_ODP O_CURSOR;
  TYPE T_ODP IS RECORD (VALOR NUMBER(22,2));               
  R_ODP T_ODP;

  V_SELECT VARCHAR2(4000);

  BEGIN

    OPEN C_ODP1;
    FETCH C_ODP1 INTO R_ODP1;
    IF C_ODP1%FOUND THEN
       VALOR := R_ODP1.VALOR;
    ELSE
       VALOR := '0';
    END IF;

    V_SELECT := 'SELECT ' || VALOR || ' VALOR FROM TARIFAS_COSTOS_DECEVAL, TIPOS_TARIFAS_COSTOS ';
    V_SELECT := V_SELECT || ' WHERE  TSD_ANO = ' || P_ANO;
    V_SELECT := V_SELECT || ' AND    TSD_TTC_MNEMONICO = ' || '''' || P_TIPO_TARIFA || '''';
    V_SELECT := V_SELECT || ' AND    TSD_TTC_MNEMONICO = TTC_MNEMONICO ';
    V_SELECT := V_SELECT || ' AND    ((TTC_RANGO = ' || '''' || 'S' || '''' || ' AND TSD_RANGO_INICIAL <= ' || TRIM(TO_CHAR(P_VALOR,'999999999999999999.99'));
    V_SELECT := V_SELECT || ' AND    TSD_RANGO_FINAL >= ' || TRIM(TO_CHAR(P_VALOR,'999999999999999999.99')) || ') ';
    V_SELECT := V_SELECT || ' OR     (TTC_RANGO = ' || '''' || 'N' || '''' || '))';

    OPEN C_ODP FOR (V_SELECT);
    FETCH C_ODP INTO R_ODP;

    IF C_ODP%FOUND THEN
       P_COSTO := R_ODP.VALOR;
    END IF;

  END;

  /**************************Proceso que genera los costos deceval****************************/
  PROCEDURE GENERAR_COSTOS_DECEVAL (P_FDESDE IN DATE, P_FHASTA IN DATE, P_COSTO IN VARCHAR2) AS

  /*****Variables*******/
  ADMINISTRA_PORTAFOLIO_DVAL      VARCHAR2(1);
  APT_CC                          VARCHAR2(1);
  COSTO                           NUMBER := 0;
  COSTO_DVP                       NUMBER := 0;
  ES_TITULO_FISICO                NUMBER := 0;
  P_NUM_INI NUMBER;
  P_NUM_FIN NUMBER; 

  /**********Procedimiento para traer los productos a los cuales se les debe calcular el costo deceval*************/
  CURSOR CUR_PRODUCTO 
  IS
    SELECT CSP_PRO_MNEMONICO
    FROM   COSTOS_PRODUCTOS
    WHERE  CSP_COS_MNEMONICO = P_COSTO;

  /**********Procedimiento para identificar si los costos deceval para las fechas indicadas ya fueron procesados********/  
  CURSOR CUR_EXISTE 
  IS
    SELECT 'X'
    FROM    OPERACIONES_DIARIAS, COSTOS_OPERACIONES_DIARIAS, LIQUIDACIONES_COMERCIAL
    WHERE   LIC_FECHA_CUMPLIMIENTO        >= P_FDESDE
    AND     LIC_FECHA_CUMPLIMIENTO        <  P_FHASTA + 1
	  AND     OPC_CONSECUTIVO               =  CPD_OPC_CONSECUTIVO
    AND     CPD_CSP_COS_MNEMONICO         = P_COSTO
    AND     OPC_LIC_BOL_MNEMONICO         = LIC_BOL_MNEMONICO
		AND     OPC_LIC_NUMERO_OPERACION      = LIC_NUMERO_OPERACION 
		AND     OPC_LIC_NUMERO_FRACCION       = LIC_NUMERO_FRACCION        
		AND     OPC_LIC_TIPO_OPERACION        = LIC_TIPO_OPERACION; 

    SINO   CUR_EXISTE%ROWTYPE;

  /**********Procedimiento para identificar si los costos deceval DVP ya existen********/  
  CURSOR CUR_EXISTE_DVP(P_NID VARCHAR2, P_TID VARCHAR2, P_ESPECIE VARCHAR2, P_FECHA_CUMPLIMIENTO DATE) 
  IS
    SELECT NID, TID, ESPECIE, FECHA_CUMPLIMIENTO
    FROM   GL_CST_DVL
    WHERE  NID                = P_NID
    AND    TID                = P_TID
	  AND    ESPECIE            = P_ESPECIE
    AND    FECHA_CUMPLIMIENTO = P_FECHA_CUMPLIMIENTO;

    SINODVP   CUR_EXISTE_DVP%ROWTYPE;

  /**********Procedimiento para traer las liquidaciones que se encuentran dentro de las fechas indicadas***********/
  CURSOR CUR_LIQUIDACIONES(PRODUCTO VARCHAR2)
  IS
    SELECT  OPC_CONSECUTIVO, OPC_PRO_MNEMONICO, CSP_COS_MNEMONICO, LIC_MERCADO, LIC_COD_CMSNSTA_CMPRDOR, LIC_COD_CMSNSTA_VNDDOR
            ,OPC_LIC_TIPO_OPERACION, OVE_CCC_CLI_PER_NUM_IDEN CLIENTEID, OVE_CCC_CLI_PER_TID_CODIGO CLIENTETID, LIC_VOLUMEN_FRACCION
            ,LIC_SUCURSAL_CUMPLIMIENTO, LIC_TIPO_OPERACION, LIC_BOL_MNEMONICO, LIC_NUMERO_OPERACION, LIC_NUMERO_FRACCION, LIC_FECHA_CUMPLIMIENTO, 
            OVE_ENA_MNEMONICO ESPECIE
    FROM    COSTOS_PRODUCTOS, ORDENES_VENTA, LIQUIDACIONES_COMERCIAL, OPERACIONES_DIARIAS
    WHERE   CSP_COS_MNEMONICO           = P_COSTO
    AND     OPC_PRO_MNEMONICO           = CSP_PRO_MNEMONICO			
		AND     OVE_BOL_MNEMONICO           = LIC_BOL_MNEMONICO       
		AND     OVE_COC_CTO_MNEMONICO       = LIC_OVE_COC_CTO_MNEMONICO    
		AND     OVE_CONSECUTIVO             = LIC_OVE_CONSECUTIVO  
 		AND     OPC_LIC_BOL_MNEMONICO       = LIC_BOL_MNEMONICO
		AND     OPC_LIC_NUMERO_OPERACION    = LIC_NUMERO_OPERACION 
		AND     OPC_LIC_NUMERO_FRACCION     = LIC_NUMERO_FRACCION        
		AND     OPC_LIC_TIPO_OPERACION      = LIC_TIPO_OPERACION     
		AND     OPC_LIC_TIPO_OPERACION      = 'V'
		AND     LIC_SUCURSAL_CUMPLIMIENTO   = 'DVL'
		AND     OPC_PRO_MNEMONICO           = PRODUCTO
		AND     LIC_FECHA_CUMPLIMIENTO      >= P_FDESDE
		AND     LIC_FECHA_CUMPLIMIENTO      <  P_FHASTA + 1
    AND     NOT EXISTS (SELECT 'X'
                        FROM   COSTOS_OPERACIONES_DIARIAS
                        WHERE  OPC_CONSECUTIVO       =  CPD_OPC_CONSECUTIVO
                        AND    CPD_CSP_COS_MNEMONICO = P_COSTO
                        AND    CPD_CSP_PRO_MNEMONICO = PRODUCTO)
    UNION ALL
    SELECT  OPC_CONSECUTIVO, OPC_PRO_MNEMONICO, CSP_COS_MNEMONICO, LIC_MERCADO, LIC_COD_CMSNSTA_CMPRDOR, LIC_COD_CMSNSTA_VNDDOR
            ,OPC_LIC_TIPO_OPERACION, OCO_CCC_CLI_PER_NUM_IDEN CLIENTEID, OCO_CCC_CLI_PER_TID_CODIGO CLIENTETID, LIC_VOLUMEN_FRACCION
            ,LIC_SUCURSAL_CUMPLIMIENTO, LIC_TIPO_OPERACION, LIC_BOL_MNEMONICO, LIC_NUMERO_OPERACION, LIC_NUMERO_FRACCION, LIC_FECHA_CUMPLIMIENTO, 
            OCO_ENA_MNEMONICO ESPECIE
    FROM    COSTOS_PRODUCTOS, ORDENES_COMPRA, LIQUIDACIONES_COMERCIAL, OPERACIONES_DIARIAS
    WHERE   CSP_COS_MNEMONICO           = P_COSTO
    AND     OPC_PRO_MNEMONICO           = CSP_PRO_MNEMONICO
		AND     OCO_BOL_MNEMONICO           = LIC_BOL_MNEMONICO       
		AND     OCO_COC_CTO_MNEMONICO       = LIC_OCO_COC_CTO_MNEMONICO    
		AND     OCO_CONSECUTIVO             = LIC_OCO_CONSECUTIVO  
		AND     OPC_LIC_BOL_MNEMONICO       = LIC_BOL_MNEMONICO
		AND     OPC_LIC_NUMERO_OPERACION    = LIC_NUMERO_OPERACION 
		AND     OPC_LIC_NUMERO_FRACCION     = LIC_NUMERO_FRACCION        
		AND     OPC_LIC_TIPO_OPERACION      = LIC_TIPO_OPERACION     
		AND     OPC_LIC_TIPO_OPERACION      = 'C'
		AND     LIC_SUCURSAL_CUMPLIMIENTO   = 'DVL'
		AND     OPC_PRO_MNEMONICO           = PRODUCTO
		AND     LIC_FECHA_CUMPLIMIENTO      >= P_FDESDE
		AND     LIC_FECHA_CUMPLIMIENTO      <  P_FHASTA + 1
    AND     NOT EXISTS (SELECT 'X'
                        FROM   COSTOS_OPERACIONES_DIARIAS
                        WHERE  OPC_CONSECUTIVO       =  CPD_OPC_CONSECUTIVO
                        AND    CPD_CSP_COS_MNEMONICO = P_COSTO
                        AND    CPD_CSP_PRO_MNEMONICO = PRODUCTO);

  /**********Procedimiento para traer movimientos ***********/
  CURSOR CUR_MOVIMIENTOS
  IS
    SELECT CCC_PER_NUM_IDEN, CCC_PER_TID_CODIGO, FUG_TIPO, MFU_FECHA
    FROM   MOVIMIENTOS_CUENTA_FUNGIBLE, CUENTAS_FUNGIBLE_CLIENTE, CUENTAS_CLIENTE_CORREDORES, FUNGIBLES
    WHERE  MFU_CFC_CUENTA_DECEVAL     = CFC_CUENTA_DECEVAL
    AND    MFU_CFC_FUG_ISI_MNEMONICO  = CFC_FUG_ISI_MNEMONICO
    AND    MFU_CFC_FUG_MNEMONICO      = CFC_FUG_MNEMONICO
    AND    CFC_CCC_CLI_PER_NUM_IDEN   = CCC_CLI_PER_NUM_IDEN
    AND    CFC_CCC_CLI_PER_TID_CODIGO = CCC_CLI_PER_TID_CODIGO
    AND    CFC_CCC_NUMERO_CUENTA      = CCC_NUMERO_CUENTA
    AND    MFU_CFC_FUG_ISI_MNEMONICO  = FUG_ISI_MNEMONICO
    AND    MFU_CFC_FUG_MNEMONICO      = FUG_MNEMONICO
    AND    (MFU_TFU_MNEMONICO         = 'INVEN' 
    OR      MFU_TFU_MNEMONICO         = 'TDCV')
    AND    MFU_FECHA                  >= P_FDESDE
    AND    MFU_FECHA                  <  P_FHASTA + 1;   

  BEGIN
    P_NUM_INI := P_TOOLS.FN_REGISTRA_PROCESO_NOCTURNO('P_COSTOS.GENERAR_COSTOS_DECEVAL','INI');
    DELETE FROM GL_CST_DVL;
    --OPEN CUR_EXISTE;
    --FETCH CUR_EXISTE INTO SINO;
    --IF CUR_EXISTE%FOUND THEN
       --DBMS_OUTPUT.PUT_LINE('Costos ya se corrieron para '||P_COSTO||' '|| 'DE '||TO_CHAR(P_FDESDE,'DD-MON-YYYY')||
                           --' HASTA '||TO_CHAR(P_FHASTA,'DD-MON-YYYY'));
    --ELSE
       FOR R_PRODUCTO IN CUR_PRODUCTO LOOP
           FOR R_LIQUIDACION IN CUR_LIQUIDACIONES (R_PRODUCTO.CSP_PRO_MNEMONICO) LOOP
               COSTO := 0;
               TITULO_FISICO (R_LIQUIDACION.LIC_BOL_MNEMONICO, R_LIQUIDACION.LIC_NUMERO_OPERACION, R_LIQUIDACION.LIC_NUMERO_FRACCION, R_LIQUIDACION.LIC_TIPO_OPERACION, ES_TITULO_FISICO);
               CLIENTE_ADMIN_DVAL(R_LIQUIDACION.CLIENTEID, R_LIQUIDACION.CLIENTETID, ADMINISTRA_PORTAFOLIO_DVAL);
               CLIENTE_APT_CC (R_LIQUIDACION.CLIENTEID, APT_CC);

               IF R_LIQUIDACION.CLIENTEID = '860079174' THEN
                  ADMINISTRA_PORTAFOLIO_DVAL := 'S';
                  APT_CC := 'N';
               ELSE
                 CLIENTE_ADMIN_DVAL(R_LIQUIDACION.CLIENTEID, R_LIQUIDACION.CLIENTETID, ADMINISTRA_PORTAFOLIO_DVAL);
                 IF ADMINISTRA_PORTAFOLIO_DVAL IS NULL THEN
                    ADMINISTRA_PORTAFOLIO_DVAL := 'N';
                 END IF;
               END IF;

               IF ES_TITULO_FISICO > 0 THEN
                  VALOR_TARIFA_COSTO ('FI', R_LIQUIDACION.LIC_VOLUMEN_FRACCION, TO_NUMBER(TO_CHAR(P_FDESDE, 'yyyy')), COSTO);
               ELSIF (R_LIQUIDACION.LIC_MERCADO = 'P' AND R_LIQUIDACION.LIC_TIPO_OPERACION = 'V') OR R_LIQUIDACION.LIC_SUCURSAL_CUMPLIMIENTO <> 'DVL' THEN
                     COSTO := 0;
               ELSIF R_PRODUCTO.CSP_PRO_MNEMONICO = 'ACC' AND ADMINISTRA_PORTAFOLIO_DVAL = 'N' THEN

                     OPEN CUR_EXISTE_DVP(R_LIQUIDACION.CLIENTEID, R_LIQUIDACION.CLIENTETID, R_LIQUIDACION.ESPECIE, R_LIQUIDACION.LIC_FECHA_CUMPLIMIENTO);
                     FETCH CUR_EXISTE_DVP INTO SINODVP;
                     IF CUR_EXISTE_DVP%NOTFOUND THEN
                        INSERT INTO GL_CST_DVL (NID, TID, ESPECIE, FECHA_CUMPLIMIENTO) 
                        VALUES (R_LIQUIDACION.CLIENTEID, R_LIQUIDACION.CLIENTETID, R_LIQUIDACION.ESPECIE, R_LIQUIDACION.LIC_FECHA_CUMPLIMIENTO);
                        VALOR_TARIFA_COSTO ('DVP', R_LIQUIDACION.LIC_VOLUMEN_FRACCION, TO_NUMBER(TO_CHAR(P_FDESDE, 'yyyy')), COSTO_DVP);
                     ELSE
                        COSTO_DVP := 0;                      
                     END IF;
                     CLOSE CUR_EXISTE_DVP;

                     IF R_LIQUIDACION.LIC_BOL_MNEMONICO = 'COL' THEN
                        VALOR_TARIFA_COSTO ('FD', R_LIQUIDACION.LIC_VOLUMEN_FRACCION, TO_NUMBER(TO_CHAR(P_FDESDE, 'yyyy')), COSTO);
                        COSTO := COSTO + COSTO_DVP;
                     ELSE
                        COSTO := COSTO_DVP;
                     END IF;

               ELSIF R_PRODUCTO.CSP_PRO_MNEMONICO = 'ACC' AND ADMINISTRA_PORTAFOLIO_DVAL = 'S' THEN
                     VALOR_TARIFA_COSTO ('FD', R_LIQUIDACION.LIC_VOLUMEN_FRACCION, TO_NUMBER(TO_CHAR(P_FDESDE, 'yyyy')), COSTO);   
               ELSIF R_PRODUCTO.CSP_PRO_MNEMONICO <> 'ACC' AND APT_CC IS NOT NULL AND APT_CC = 'S' AND (R_LIQUIDACION.LIC_COD_CMSNSTA_CMPRDOR||R_LIQUIDACION.LIC_COD_CMSNSTA_VNDDOR) = '002002' THEN
                     VALOR_TARIFA_COSTO ('DVP', R_LIQUIDACION.LIC_VOLUMEN_FRACCION, TO_NUMBER(TO_CHAR(P_FDESDE, 'yyyy')), COSTO);   
               ELSIF R_PRODUCTO.CSP_PRO_MNEMONICO <> 'ACC' AND ADMINISTRA_PORTAFOLIO_DVAL = 'N' AND (R_LIQUIDACION.LIC_COD_CMSNSTA_CMPRDOR||R_LIQUIDACION.LIC_COD_CMSNSTA_VNDDOR) = '002002' THEN
                     VALOR_TARIFA_COSTO ('DVP', R_LIQUIDACION.LIC_VOLUMEN_FRACCION, TO_NUMBER(TO_CHAR(P_FDESDE, 'yyyy')), COSTO);   
               ELSIF R_PRODUCTO.CSP_PRO_MNEMONICO <> 'ACC' AND ADMINISTRA_PORTAFOLIO_DVAL = 'S' AND (R_LIQUIDACION.LIC_COD_CMSNSTA_CMPRDOR||R_LIQUIDACION.LIC_COD_CMSNSTA_VNDDOR) = '002002' THEN
                     VALOR_TARIFA_COSTO ('FD', R_LIQUIDACION.LIC_VOLUMEN_FRACCION, TO_NUMBER(TO_CHAR(P_FDESDE, 'yyyy')), COSTO);   
               ELSIF R_PRODUCTO.CSP_PRO_MNEMONICO <> 'ACC' AND (R_LIQUIDACION.LIC_COD_CMSNSTA_CMPRDOR||R_LIQUIDACION.LIC_COD_CMSNSTA_VNDDOR) <> '002002' THEN
                     VALOR_TARIFA_COSTO ('DVP', R_LIQUIDACION.LIC_VOLUMEN_FRACCION, TO_NUMBER(TO_CHAR(P_FDESDE, 'yyyy')), COSTO);
               END IF;

               COSTO := NVL(COSTO, 0);

               INSERT INTO  COSTOS_OPERACIONES_DIARIAS (CPD_OPC_CONSECUTIVO, CPD_CSP_PRO_MNEMONICO
                                                      ,CPD_CSP_COS_MNEMONICO, CPD_COSTO)
               VALUES (R_LIQUIDACION.OPC_CONSECUTIVO, R_PRODUCTO.CSP_PRO_MNEMONICO, R_LIQUIDACION.CSP_COS_MNEMONICO, COSTO);
           END LOOP;
       END LOOP;

       FOR R_MOVIMIENTOS IN CUR_MOVIMIENTOS LOOP
           COSTO := 0;
           VALOR_TARIFA_COSTO ('FD', 0, TO_NUMBER(TO_CHAR(P_FDESDE, 'yyyy')), COSTO);   
           INSERT INTO  COSTOS_MOVIMIENTOS_FUNGIBLES (CMF_CONSECUTIVO, CMF_COSTO, CMF_PER_NUM_IDEN, CMF_PER_TID_CODIGO, CMF_CSP_PRO_MNEMONICO, CMF_CSP_COS_MNEMONICO, CMF_FECHA)
           VALUES (CMF_SEQ.NEXTVAL, COSTO, R_MOVIMIENTOS.CCC_PER_NUM_IDEN, R_MOVIMIENTOS.CCC_PER_TID_CODIGO, R_MOVIMIENTOS.FUG_TIPO, 'DAOP', R_MOVIMIENTOS.MFU_FECHA);
       END LOOP;       
       COMMIT;
    --END IF;
   P_NUM_FIN := P_TOOLS.FN_REGISTRA_PROCESO_NOCTURNO('P_COSTOS.GENERAR_COSTOS_DECEVAL','FIN');

   COMMIT;

  END GENERAR_COSTOS_DECEVAL;



PROCEDURE P_DIRECCION_CORRESPONDENCIA_E 
 (P_NUM_IDEN IN VARCHAR2
 ,P_TID_CODIGO IN VARCHAR2
 ,P_DIRECCION OUT VARCHAR2
 ,P_TELEFONO OUT VARCHAR2
 ,P_CIUDAD OUT VARCHAR2
 ,P_CIUDAD_DECEVAL  OUT NUMBER 
 ,P_DEPARTAMENTO_DECEVAL OUT NUMBER
 ,P_PAIS_DECEVAL OUT VARCHAR2
 ,P_PAIS OUT VARCHAR2
 ,P_EMAIL OUT VARCHAR2
 ,P_DEPARTAMENTO OUT VARCHAR2
 ,P_DANE OUT VARCHAR2
 )
 IS
   CURSOR C_CLIENTE IS
      SELECT PER_TIPO
            ,CLI_DIRECCION_OFICINA
            ,CLI_AGE_CODIGO_TRABAJA
            ,AGE1.AGE_CIUDAD     AGE_CIUDAD_TRABAJA
            ,CLI_TELEFONO_OFICINA
            ,CLI_DIRECCION_RESIDENCIA
            ,CLI_AGE_CODIGO_RESIDE
            ,AGE2.AGE_CIUDAD     AGE_CIUDAD_RESIDE
            ,CLI_TELEFONO_RESIDENCIA
            ,CLI_TEC_MNEMONICO
            ,AGE1.AGE_PAIS_DECEVAL AGE_PAIS_DEC_T
            ,AGE1.AGE_DEPARTAMENTO_DECEVAL AGE_DEPARTAMENTO_DEC_T
            ,AGE1.AGE_CIUDAD_DECEVAL AGE_CIUDAD_DEC_T
            ,AGE1.AGE_PAIS AGE_PAIS_T
            ,AGE1.AGE_DEPARTAMENTO AGE_DEPARTAMENTO_T
            ,AGE2.AGE_PAIS_DECEVAL AGE_PAIS_DEC_R
            ,AGE2.AGE_DEPARTAMENTO_DECEVAL AGE_DEPARTAMENTO_DEC_R
            ,AGE2.AGE_CIUDAD_DECEVAL AGE_CIUDAD_DEC_R
            ,AGE2.AGE_PAIS AGE_PAIS_R
            ,AGE2.AGE_DEPARTAMENTO AGE_DEPARTAMENTO_R            
            ,P_CORREOS_COEASY.P_CORREO(CLI_PER_TID_CODIGO,CLI_PER_NUM_IDEN,'P') CLI_DIRECCION_EMAIL
      FROM   AREAS_GEOGRAFICAS AGE1
            ,AREAS_GEOGRAFICAS AGE2
            ,PERSONAS
            ,CLIENTES
      WHERE  AGE1.AGE_CODIGO (+) = CLI_AGE_CODIGO_TRABAJA
      AND    AGE2.AGE_CODIGO (+) = CLI_AGE_CODIGO_RESIDE
      AND    CLI_PER_NUM_IDEN = PER_NUM_IDEN
      AND    CLI_PER_TID_CODIGO = PER_TID_CODIGO
      AND    PER_NUM_IDEN = P_NUM_IDEN
      AND    PER_TID_CODIGO = P_TID_CODIGO;
   CLI1   C_CLIENTE%ROWTYPE;
BEGIN
   OPEN C_CLIENTE;
   FETCH C_CLIENTE INTO CLI1;
   IF C_CLIENTE%FOUND THEN
      IF CLI1.CLI_TEC_MNEMONICO = 'OFI' THEN
         P_DIRECCION := CLI1.CLI_DIRECCION_OFICINA;
         P_TELEFONO := CLI1.CLI_TELEFONO_OFICINA;
         P_CIUDAD := CLI1.AGE_CIUDAD_TRABAJA;
         P_CIUDAD_DECEVAL   := CLI1.AGE_CIUDAD_DEC_T;
         P_DEPARTAMENTO_DECEVAL := CLI1.AGE_DEPARTAMENTO_DEC_T;
         P_PAIS_DECEVAL     := CLI1.AGE_PAIS_DEC_T;
         P_PAIS :=  CLI1.AGE_PAIS_T;
         P_DEPARTAMENTO := CLI1.AGE_DEPARTAMENTO_T;
         P_EMAIL := CLI1.CLI_DIRECCION_EMAIL;
      ELSIF CLI1.CLI_TEC_MNEMONICO = 'RES' THEN
         P_DIRECCION := CLI1.CLI_DIRECCION_RESIDENCIA;
         P_TELEFONO := CLI1.CLI_TELEFONO_RESIDENCIA;
         P_CIUDAD := CLI1.AGE_CIUDAD_RESIDE;
         P_CIUDAD_DECEVAL   := CLI1.AGE_CIUDAD_DEC_R;
         P_DEPARTAMENTO_DECEVAL := CLI1.AGE_DEPARTAMENTO_DEC_R;
         P_PAIS_DECEVAL     := CLI1.AGE_PAIS_DEC_R;
         P_PAIS :=  CLI1.AGE_PAIS_R;
         P_DEPARTAMENTO := CLI1.AGE_DEPARTAMENTO_R;
         P_EMAIL := CLI1.CLI_DIRECCION_EMAIL;         
      ELSE
         IF CLI1.PER_TIPO = 'PJU' THEN
            P_DIRECCION := CLI1.CLI_DIRECCION_OFICINA;
            P_TELEFONO := CLI1.CLI_TELEFONO_OFICINA;
            P_CIUDAD := CLI1.AGE_CIUDAD_TRABAJA;
            P_CIUDAD_DECEVAL   := CLI1.AGE_CIUDAD_DEC_T;
            P_DEPARTAMENTO_DECEVAL := CLI1.AGE_DEPARTAMENTO_DEC_T;
            P_PAIS_DECEVAL     := CLI1.AGE_PAIS_DEC_T;
            P_PAIS :=  CLI1.AGE_PAIS_T;
            P_DEPARTAMENTO := CLI1.AGE_DEPARTAMENTO_T;
            P_EMAIL := CLI1.CLI_DIRECCION_EMAIL;            
         ELSE
            P_DIRECCION := CLI1.CLI_DIRECCION_RESIDENCIA;
            P_TELEFONO := CLI1.CLI_TELEFONO_RESIDENCIA;
            P_CIUDAD := CLI1.AGE_CIUDAD_RESIDE;
            P_CIUDAD_DECEVAL   := CLI1.AGE_CIUDAD_DEC_R;
            P_DEPARTAMENTO_DECEVAL := CLI1.AGE_DEPARTAMENTO_DEC_R;
            P_PAIS_DECEVAL     := CLI1.AGE_PAIS_DEC_R;
            P_PAIS :=  CLI1.AGE_PAIS_R;
            P_DEPARTAMENTO := CLI1.AGE_DEPARTAMENTO_R;
            P_EMAIL := CLI1.CLI_DIRECCION_EMAIL;
         END IF;
      END IF;
    ELSE
       P_DIRECCION := NULL;
       P_TELEFONO := NULL;
       P_CIUDAD := NULL;
       P_CIUDAD_DECEVAL   := NULL;
       P_DEPARTAMENTO_DECEVAL := NULL;
       P_PAIS_DECEVAL     := NULL;
       P_PAIS := NULL;
       P_DEPARTAMENTO := NULL;
       P_EMAIL := NULL;
    END IF;
    P_DANE := LPAD(P_CIUDAD_DECEVAL,2,'0')||LPAD(P_DEPARTAMENTO_DECEVAL,3,'0');
END P_DIRECCION_CORRESPONDENCIA_E;

/**********Procedimiento para costos MEC : servicio de bolsa fijo y variable de liquidaciones ********/  
PROCEDURE PR_COSTOS_MEC (P_FECHA IN DATE,
                        P_PRODUCTO IN VARCHAR2) IS

   -- VARIABLES PARA MAIL
   conn                    utl_smtp.connection;
   req                     utl_http.req;  
   resp                    utl_http.resp;
   data                    RAW(200);
   NOM_ERROR    VARCHAR2(80); 
   P_NUM_INI NUMBER;
   P_NUM_FIN NUMBER; 

   -- CURSOR DE TODAS LAS OPERACIONES EN EL RANGO DE FECHAS

   CURSOR OPE(PRO VARCHAR2) IS
      SELECT OPC_CONSECUTIVO,
             OPC_FECHA,
             OPC_PRO_MNEMONICO,
             OPC_LIC_BOL_MNEMONICO,
             OPC_LIC_NUMERO_OPERACION,
             OPC_LIC_NUMERO_FRACCION,
             OPC_LIC_TIPO_OPERACION,
             OPC_PRF_FON_CODIGO,
             OPC_PRF_CONSECUTIVO,
             OPC_ORD_SUC_CODIGO,
             OPC_ORD_CONSECUTIVO,
             OPC_OFO_SUC_CODIGO,
             OPC_OFO_CONSECUTIVO,
             OPC_ODP_SUC_CODIGO,
             OPC_ODP_CONSECUTIVO,
             OPC_ODP_NEG_CONSECUTIVO,
             OPC_MCC_CONSECUTIVO
       FROM OPERACIONES_DIARIAS,
            LIQUIDACIONES_CARGOS
       WHERE OPC_LIC_BOL_MNEMONICO = LCR_BOL_MNEMONICO
         AND OPC_LIC_NUMERO_OPERACION = LCR_NUMERO_OPERACION
         AND OPC_LIC_TIPO_OPERACION = LCR_TIPO_OPERACION
         AND LCR_FECHA >= TRUNC(P_FECHA)
         AND LCR_FECHA <  TRUNC(P_FECHA + 1)
         AND OPC_PRO_MNEMONICO = PRO;

   R_OPE OPE%ROWTYPE;

   HAY_COSTO VARCHAR2(1);
   DIAS NUMBER;


   -- COSTOS DE TIPO GENERAL ASOCIADOS AL PRODUCTO
   CURSOR COSTO(PRO VARCHAR2)  IS
      SELECT CSP_PRO_MNEMONICO,
             CSP_COS_MNEMONICO,
             COS_TCO_MNEMONICO,
             CSP_VALOR,
             replace(rtrim(csp_formula),' ') FORMULA
      FROM COSTOS_PRODUCTOS,
           COSTOS
      WHERE CSP_COS_MNEMONICO = COS_MNEMONICO
        AND CSP_PRO_MNEMONICO = PRO
        AND COS_TCO_MNEMONICO = 'G'
        AND CSP_COS_MNEMONICO = 'MEC';
   R_COSTO COSTO%ROWTYPE;

   -- CURSORES USADOS PARA CALCULAR EL COSTO EN CASO DE QUE SEA UNA FORMULA 
   CURSOR LONG(PRO VARCHAR2, COS VARCHAR2) IS
      SELECT length(replace(rtrim(csp_formula),' '))
      FROM COSTOS_PRODUCTOS
      WHERE CSP_PRO_MNEMONICO = PRO
        AND CSP_COS_MNEMONICO = COS;

   LONGITUD NUMBER;
   NUM NUMBER;

   CURSOR CAR(FORM VARCHAR2, N NUMBER) IS
      SELECT SUBSTR(FORM, N, 1)
      FROM DUAL;
   CAR1 VARCHAR2(1);

   CURSOR TABLA (AL VARCHAR2) IS
      SELECT TABLE_NAME
      FROM USER_CONSTRAINTS
      WHERE CONSTRAINT_NAME = SUBSTR(AL,1,3)||'_PK';
   NTABLA VARCHAR2(50);

   CADENA1 VARCHAR2(200);
   ALIAS VARCHAR2(50);
   CADENA2 VARCHAR2(200);
   v_COSTO NUMBER;
   v_VALOR NUMBER;
   CAD_QRY VARCHAR2(600);
   SOURCE_CURSOR  INTEGER;
   IGNORE         NUMBER;

BEGIN
   P_NUM_INI := P_TOOLS.FN_REGISTRA_PROCESO_NOCTURNO('P_COSTOS.PR_COSTOS_MEC','INI');
   OPEN OPE(P_PRODUCTO);
   FETCH OPE INTO R_OPE;
   WHILE OPE%FOUND LOOP
      DELETE FROM COSTOS_OPERACIONES_DIARIAS
      WHERE CPD_OPC_CONSECUTIVO = R_OPE.OPC_CONSECUTIVO
        AND CPD_CSP_COS_MNEMONICO = 'MEC';

      OPEN COSTO(R_OPE.OPC_PRO_MNEMONICO);
      FETCH COSTO INTO R_COSTO;
      WHILE COSTO%FOUND LOOP
         V_COSTO := 0;
         V_VALOR := 0;
         IF R_COSTO.CSP_VALOR IS NOT NULL THEN  -- EL COSTO ES UN VALOR
            V_COSTO := R_COSTO.CSP_VALOR;
         ELSE                                   -- EL COSTO SE CALCULA CON UNA FORMULA Y SE DETERMINA DE QUE TABLA SON LOS CAMPOS
            OPEN LONG(R_COSTO.CSP_PRO_MNEMONICO,
                      R_COSTO.CSP_COS_MNEMONICO);
            FETCH LONG INTO LONGITUD;
            CLOSE LONG;
            NUM := 0;
            CAD_QRY := '';
            CADENA1 := '';
            ALIAS := '';
            WHILE LONGITUD != 0 LOOP
               CAR1:= '';
               NUM := NUM + 1;
               OPEN CAR(R_COSTO.FORMULA,
                        NUM);
               FETCH CAR INTO CAR1;
               CLOSE CAR;
               IF CAR1 IN ('0','1','2','3','4','5','6','7','8','9','(',')','+','-','*','/','.') THEN
                  CADENA1 := CADENA1||CAR1;
               END IF;
               IF CAR1 BETWEEN 'A' AND 'Z' OR CAR1 = '_' THEN
                  CADENA2 := CAR1;
                  WHILE CAR1 BETWEEN 'A' AND 'Z' OR CAR1 = '_' LOOP
                     CAR1 := '';
                     NUM := NUM + 1;
                     OPEN CAR(R_COSTO.FORMULA, NUM);
                     FETCH CAR INTO CAR1;
                     CLOSE CAR;
                     IF CAR1 IN ('0','1','2','3','4','5','6','7','8','9','(',')','+','-','*','/','.') THEN
                        EXIT;
                     ELSE
                        CADENA2 := CADENA2||CAR1;
                     END IF;
                     LONGITUD := LONGITUD - 1;
                  END LOOP;
                  ALIAS := SUBSTR(CADENA2,1,3);
                  CADENA1 := CADENA1||CADENA2||CAR1;
               END IF;
               LONGITUD := LONGITUD - 1;
            END LOOP;
            OPEN TABLA(ALIAS);
            FETCH TABLA INTO NTABLA;
            IF TABLA%NOTFOUND THEN
               NTABLA := 'DUAL';
            ELSE
               NTABLA := NVL(NTABLA,'');
            END IF;
            CLOSE TABLA;
            IF ALIAS = 'LIC' AND R_OPE.OPC_LIC_NUMERO_OPERACION IS NOT NULL THEN
               CAD_QRY := 'SELECT '||CADENA1||
                          ' FROM LIQUIDACIONES_COMERCIAL '||
                          ' WHERE LIC_BOL_MNEMONICO   = '||''''||R_OPE.OPC_LIC_BOL_MNEMONICO||''''||
                          '   AND LIC_NUMERO_OPERACION= '||''''||R_OPE.OPC_LIC_NUMERO_OPERACION||''''||
                          '   AND LIC_NUMERO_FRACCION = '||      R_OPE.OPC_LIC_NUMERO_FRACCION ||
                          '   AND LIC_TIPO_OPERACION  = '||''''||R_OPE.OPC_LIC_TIPO_OPERACION||'''';
            END IF;
            IF CAD_QRY IS NOT NULL THEN
               BEGIN  -- QUERY PARA CALCULAR EL COSTO DE LA OPERACION
                  SOURCE_CURSOR := DBMS_SQL.OPEN_CURSOR;
                  DBMS_SQL.PARSE(SOURCE_CURSOR,CAD_QRY,2);
                  DBMS_SQL.DEFINE_COLUMN(SOURCE_CURSOR, 1, V_VALOR);
                  IGNORE := DBMS_SQL.EXECUTE(source_cursor);
                  IF DBMS_SQL.FETCH_ROWS(source_cursor) > 0 THEN
                     DBMS_SQL.COLUMN_VALUE(source_cursor, 1, V_VALOR);
                  END IF;
                  DBMS_SQL.CLOSE_CURSOR(source_cursor); 
                  V_COSTO := V_VALOR;
               END;
            END IF;
         END IF;

         IF V_COSTO != 0 THEN
            IF R_COSTO.COS_TCO_MNEMONICO = 'G' THEN
               INSERT INTO COSTOS_OPERACIONES_DIARIAS
                         (CPD_OPC_CONSECUTIVO,
                          CPD_CSP_PRO_MNEMONICO,
                          CPD_CSP_COS_MNEMONICO,
                          CPD_COSTO)
               VALUES (R_OPE.OPC_CONSECUTIVO,
                          R_COSTO.CSP_PRO_MNEMONICO,
                          R_COSTO.CSP_COS_MNEMONICO,
                          V_COSTO);
            END IF;
         END IF;
         FETCH COSTO INTO R_COSTO;
      END LOOP;
      CLOSE COSTO;
      COMMIT;      
      FETCH OPE INTO R_OPE;
   END LOOP;
   CLOSE OPE;
   P_NUM_FIN := P_TOOLS.FN_REGISTRA_PROCESO_NOCTURNO('P_COSTOS.PR_COSTOS_MEC','FIN');

   COMMIT;   

exception
    when OTHERS then 
    P_MAIL.envio_mail_error('Error en procedimiento P_COSTOS.PR_COSTOS_MEC',substr(sqlerrm,1,80));
END PR_COSTOS_MEC;
END P_COSTOS;

/

  GRANT EXECUTE ON "PROD"."P_COSTOS" TO "COE_RECURSOS";
