--------------------------------------------------------
--  File created - Sunday-April-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body P_INACTIVA_CLIENTES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PROD"."P_INACTIVA_CLIENTES" IS
  
PROCEDURE INACTIVAR_CLIENTES_UNICA_OP IS  
  
   CURSOR C_CONSTANTE IS
      SELECT CON_VALOR
      FROM CONSTANTES
      WHERE CON_MNEMONICO = 'DIC';
   DIAS NUMBER;

   CURSOR C_CLI (PFECHA DATE) IS
      SELECT CLI_PER_NUM_IDEN,
             CLI_PER_TID_CODIGO,
             CLI_ECL_MNEMONICO,
             CLI_CLIENTE_DAFUTURO
      FROM CLIENTES
      WHERE NVL(CLI_UNICA_OPERACION,'N') = 'S'
        AND CLI_FECHA_APERTURA <= TRUNC(PFECHA)
        AND (CLI_ECL_MNEMONICO IN  ('ACC','ACI')
              OR (CLI_ECL_MNEMONICO = 'BAA' AND CLI_MOI_MNEMONICO = 'PBU'));
                                    
   R_CLI C_CLI%ROWTYPE;
   P_FECHA DATE;   -- FECHA DESDE LA CUAL SE INACTIVARAN LOS CLIENTES
   P_FECHA_HOY DATE;   -- FECHA DE ACTUALIZACION
   P_USUARIO VARCHAR2(20):= 'AUTOMATICO';  -- USUARIO CON EL QUE QUEDA LA ACTUALIZACION
   TIENE_SALDO VARCHAR2(1);  -- INDICA SI EL CLIENTE TIENE SALDO O NO  
   NO_CONSTANTE EXCEPTION;
BEGIN
   OPEN C_CONSTANTE;
   FETCH C_CONSTANTE INTO DIAS;
   IF C_CONSTANTE%NOTFOUND THEN
      RAISE NO_CONSTANTE;
   END IF;
   CLOSE C_CONSTANTE;

   SELECT SYSDATE- DIAS INTO P_FECHA FROM DUAL;
   SELECT SYSDATE INTO P_FECHA_HOY FROM DUAL;

   OPEN C_CLI (P_FECHA);
   FETCH C_CLI INTO R_CLI;
   WHILE C_CLI%FOUND LOOP
      TIENE_SALDO := P_INACTIVA_CLIENTES.VALIDA_SALDO(R_CLI.CLI_PER_NUM_IDEN, R_CLI.CLI_PER_TID_CODIGO);    
      IF TIENE_SALDO = 'S' THEN
         IF  R_CLI.CLI_ECL_MNEMONICO != 'BAA' THEN
            UPDATE CLIENTES
            SET  CLI_ECL_MNEMONICO              = 'BAA'   -- SI TIENE SALDO SE COLOCA ESTADO DE BLOQUEADO POR AREA ADMINISTRATIVA
      	        ,CLI_FECHA_ULTIMA_MODIFICACION  = P_FECHA_HOY
                ,CLI_USUARIO_ULTIMA_MODIFICA    = P_USUARIO
                ,CLI_ULTIMA_OPERACION_EJECUTADA = 'MO'
                ,CLI_MOI_MNEMONICO              = 'PBU'
            WHERE CLI_PER_NUM_IDEN = R_CLI.CLI_PER_NUM_IDEN
              AND CLI_PER_TID_CODIGO = R_CLI.CLI_PER_TID_CODIGO;
         END IF;
      ELSE
      	 -- SI NO TIENE SALDO DE INACTIVA EL CLIENTE
         IF NVL(R_CLI.CLI_CLIENTE_DAFUTURO,'N') = 'N' THEN
            P_INACTIVA_CLIENTES.INACTIVA_CLIENTE(R_CLI.CLI_PER_NUM_IDEN,R_CLI.CLI_PER_TID_CODIGO); 
         END IF;
      END IF;      
      FETCH C_CLI INTO R_CLI;
   END LOOP;
   CLOSE C_CLI;
   COMMIT;  
   
EXCEPTION
	WHEN NO_CONSTANTE THEN
		RAISE_APPLICATION_ERROR(-20001,'No existe constante No DIAS INACTIVAR CLIENTES UNICA OPERAC.');
END INACTIVAR_CLIENTES_UNICA_OP;


FUNCTION VALIDA_SALDO (N_IDEN VARCHAR2,
                       T_IDEN VARCHAR2) RETURN VARCHAR2 IS
                     
   CON_SALDO VARCHAR2(1) := 'N';                       

   CURSOR CCC IS
      SELECT  CCC_SALDO_CAPITAL
             ,CCC_SALDO_A_PLAZO
             ,CCC_SALDO_A_CONTADO
             ,CCC_SALDO_ADMON_VALORES
             ,CCC_SALDO_CANJE
             ,CCC_SALDO_BURSATIL
      FROM CUENTAS_CLIENTE_CORREDORES
      WHERE CCC_CLI_PER_NUM_IDEN = N_IDEN
        AND CCC_CLI_PER_TID_CODIGO = T_IDEN;        
   R_CCC CCC%ROWTYPE;

   CURSOR CDV IS
      SELECT  CDV_SALDO              
             ,CDV_SALDO_RESTRINGIDO
      FROM CUENTAS_CLIENTES_DIVISAS
      WHERE CDV_CCC_CLI_PER_NUM_IDEN = N_IDEN
        AND CDV_CCC_CLI_PER_TID_CODIGO = T_IDEN;        
   R_CDV CDV%ROWTYPE;


   CURSOR CFO IS
      SELECT CFO_SALDO_INVER
      FROM FONDOS,
           CUENTAS_FONDOS
      WHERE FON_CODIGO = CFO_FON_CODIGO
        AND FON_TIPO != 'O'
        AND CFO_CCC_CLI_PER_NUM_IDEN = N_IDEN
        AND CFO_CCC_CLI_PER_TID_CODIGO = T_IDEN;

   R_CFO CFO%ROWTYPE;  

   CURSOR CFO_CORRESPONSAL IS
      SELECT CFO_SALDO_UNIDADES
      FROM FONDOS,
           CUENTAS_FONDOS
      WHERE FON_CODIGO = CFO_FON_CODIGO
        AND FON_TIPO   = 'O'
        AND CFO_CCC_CLI_PER_NUM_IDEN = N_IDEN
        AND CFO_CCC_CLI_PER_TID_CODIGO = T_IDEN;

   R_CFO_CORRESPONSAL CFO_CORRESPONSAL%ROWTYPE;  

   CURSOR CFC IS
     SELECT  CFC_SALDO_CLIENTE
            ,CFC_SALDO_DCVAL_GAR_REPO       
            ,CFC_SALDO_DCVAL_POR_CUMPLIR    
			,CFC_SALDO_COMPRA_X_CUMPLIR
            ,CFC_SALDO_DCVAL_GARANTIA_DER 	
     FROM CUENTAS_FUNGIBLE_CLIENTE
     WHERE CFC_CCC_CLI_PER_NUM_IDEN    = N_IDEN
       AND CFC_CCC_CLI_PER_TID_CODIGO  = T_IDEN;
    R_CFC CFC%ROWTYPE;

   CURSOR TIT IS
       SELECT 'X'
       FROM TITULOS TIT,
            ESTADOS_TITULO_COMERCIAL ETC
       WHERE ETC.ETC_DESACTIVA_TITULO = 'N'
         AND TIT.TLO_ETC_MNEMONICO = ETC.ETC_MNEMONICO
         AND TIT.TLO_CCC_CLI_PER_NUM_IDEN = N_IDEN
         AND TIT.TLO_CCC_CLI_PER_TID_CODIGO = T_IDEN
         AND NVL(TIT.TLO_PORTAFOLIO,'N') = 'S';
   COND_TIT VARCHAR2(1);
   
   -- FISICOS
   CURSOR FISICOS IS
       SELECT 'X'
       FROM TITULOS TIT,
            ESTADOS_TITULO_COMERCIAL ETC
       WHERE ETC.ETC_DESACTIVA_TITULO = 'N'
         AND TIT.TLO_ETC_MNEMONICO = ETC.ETC_MNEMONICO
         AND TIT.TLO_CCC_CLI_PER_NUM_IDEN = N_IDEN
         AND TIT.TLO_CCC_CLI_PER_TID_CODIGO = T_IDEN
         AND TLO_LTI_MNEMONICO = 'FI';
   COND_TIT_FISICO VARCHAR2(1);

 
  -- VAGTUS014652 - REVISION INACTIVACION PROCESO AUTOMATICO 
  -- VERIFICACION SALDO POR MONETIZAR
  CURSOR C_SCM IS
      SELECT 'X'
      FROM   SALDOS_CLIENTES_MONETIZAR
      WHERE  SCM_CCC_CLI_PER_NUM_IDEN = N_IDEN
      AND    SCM_CCC_CLI_PER_TID_CODIGO = T_IDEN
      AND    SCM_SALDO_MONETIZAR != 0;              
  COND_SCM VARCHAR2(1);    
  -- FIN VAGTUS014652

BEGIN
   -- VERIFICACION DE SALDOS EN CORREDORES
   OPEN CCC;
   FETCH CCC INTO R_CCC;
   WHILE CCC%FOUND AND CON_SALDO = 'N' LOOP
      IF (R_CCC.CCC_SALDO_CAPITAL != 0 
          OR R_CCC.CCC_SALDO_A_PLAZO  != 0    
          OR R_CCC.CCC_SALDO_A_CONTADO != 0    
          OR R_CCC.CCC_SALDO_ADMON_VALORES  != 0
          OR R_CCC.CCC_SALDO_CANJE != 0
          OR R_CCC.CCC_SALDO_BURSATIL != 0) THEN
         CON_SALDO := 'S';   
      ELSE
         CON_SALDO := 'N';
      END IF;
      FETCH CCC INTO R_CCC;
   END LOOP;
   CLOSE CCC;
  
  
   -- VERIFICACION DE SALDOS EN DIVISAS  
   IF CON_SALDO = 'N' THEN      
      OPEN CDV;
      FETCH CDV INTO R_CDV;
      WHILE CDV%FOUND AND CON_SALDO = 'N' LOOP
         IF (   R_CDV.CDV_SALDO != 0 
             OR R_CDV.CDV_SALDO_RESTRINGIDO  != 0 ) THEN
            CON_SALDO := 'S';   
         ELSE
            CON_SALDO := 'N';
         END IF;
         FETCH CDV INTO R_CDV;
      END LOOP;
      CLOSE CDV;
   END IF;

   -- VERIFICACION SALDOS EN FONDOS
   IF CON_SALDO = 'N' THEN      
      OPEN CFO;
      FETCH CFO INTO R_CFO;
      WHILE CFO%FOUND AND CON_SALDO = 'N' LOOP
         IF (R_CFO.CFO_SALDO_INVER != 0 ) THEN                   
            CON_SALDO := 'S';  
         ELSE
            CON_SALDO := 'N';
         END IF;
         FETCH CFO INTO R_CFO;
      END LOOP;            
      CLOSE CFO;
   END IF; 

   -- VERIFICACION SALDOS EN FONDOS- CORRESPONSALIAS
   IF CON_SALDO = 'N' THEN      
      OPEN CFO_CORRESPONSAL;
      FETCH CFO_CORRESPONSAL INTO R_CFO_CORRESPONSAL;
      WHILE CFO_CORRESPONSAL%FOUND AND CON_SALDO = 'N' LOOP
         IF ( R_CFO_CORRESPONSAL.CFO_SALDO_UNIDADES != 0 ) THEN 
             CON_SALDO := 'S';  
          ELSE
             CON_SALDO := 'N';
          END IF;
          FETCH CFO_CORRESPONSAL INTO R_CFO_CORRESPONSAL;
      END LOOP;            
      CLOSE CFO_CORRESPONSAL;
   END IF; 

   -- VERIFICACION SALDOS EN DECEVAL
   IF CON_SALDO = 'N' THEN      
      OPEN CFC;
      FETCH CFC INTO R_CFC;
      WHILE CFC%FOUND AND CON_SALDO = 'N' LOOP
         IF (   R_CFC.CFC_SALDO_CLIENTE != 0 
             OR R_CFC.CFC_SALDO_DCVAL_GAR_REPO != 0 
             OR R_CFC.CFC_SALDO_DCVAL_POR_CUMPLIR  != 0
			 OR R_CFC.CFC_SALDO_COMPRA_X_CUMPLIR  != 0
             OR R_CFC.CFC_SALDO_DCVAL_GARANTIA_DER 	!= 0)  THEN
            CON_SALDO := 'S';  
         ELSE
            CON_SALDO := 'N';
         END IF;
         FETCH CFC INTO R_CFC;
      END LOOP;
      CLOSE CFC;
   END IF; 

   -- VERIFICACION DE TITULOS 
   IF CON_SALDO = 'N' THEN      
      COND_TIT := NULL;
      OPEN TIT;
      FETCH TIT INTO COND_TIT;
      CLOSE TIT;
      IF NVL(COND_TIT,' ') = 'X' THEN
         CON_SALDO := 'S';  
      ELSE
         CON_SALDO := 'N';
      END IF;
   END IF;

   -- VERIFICACION DE TITULOS FISICOS
   IF CON_SALDO = 'N' THEN      
      COND_TIT_FISICO := NULL;
      OPEN FISICOS;
      FETCH FISICOS INTO COND_TIT_FISICO;
      CLOSE FISICOS;
      IF NVL(COND_TIT_FISICO,' ') = 'X' THEN
         CON_SALDO := 'S';  
      ELSE
         CON_SALDO := 'N';
      END IF;
   END IF;
 
   -- VAGTUS014652 - REVISION INACTIVACION PROCESO AUTOMATICO 
   -- VERIFICACION SALDO POR MONETIZAR
   IF CON_SALDO = 'N' THEN      
      COND_SCM := NULL;
      OPEN C_SCM ();
      FETCH C_SCM INTO COND_SCM;
      CLOSE C_SCM;
      IF NVL(COND_SCM,' ') = 'X' THEN
         CON_SALDO := 'S';  
      ELSE
         CON_SALDO := 'N';
      END IF;
   END IF;
  -- FIN VAGTUS014652
 
   RETURN(NVL(CON_SALDO,'N'));
END VALIDA_SALDO;

PROCEDURE INACTIVA_CLIENTE (N_IDEN VARCHAR2,
                            T_IDEN VARCHAR2) IS
   FECHA_HOY DATE;    
   P_USUARIO VARCHAR2(20) := 'AUTOMATICO';  --USUARIO CON QUE SE INACTIVA EL CLIENTE                        
BEGIN
	 SELECT SYSDATE INTO FECHA_HOY FROM DUAL;
   BEGIN
      INSERT INTO CLIENTES_INACTIVOS
               (CIN_FECHA,
                CIN_CLI_PER_NUM_IDEN,
                CIN_CLI_PER_TID_CODIGO,
                CIN_USUARIO)
      VALUES 
               (FECHA_HOY,
                N_IDEN,
                T_IDEN,
                P_USUARIO);
                  
   EXCEPTION 
      WHEN OTHERS THEN
         RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE: '||sqlerrm);
   END;
           
   -- INACTIVACION CLIENTE
   BEGIN
      UPDATE CLIENTES
      SET  CLI_ECL_MNEMONICO              = 'INA'
      	  ,CLI_FECHA_ULTIMA_MODIFICACION  = FECHA_HOY
          ,CLI_USUARIO_ULTIMA_MODIFICA    = P_USUARIO
		  ,CLI_FECHA_INACTIVACION  = FECHA_HOY
          ,CLI_USUARIO_INACTIVACION    = P_USUARIO
          ,CLI_ULTIMA_OPERACION_EJECUTADA = 'MO'
          ,CLI_MOI_MNEMONICO              = 'PIU'
      WHERE CLI_PER_NUM_IDEN = N_IDEN
        AND CLI_PER_TID_CODIGO = T_IDEN;
                 
   EXCEPTION WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE actualizando CLIENTES: '||sqlerrm);
   END;             

   -- INACTIVACION PERSONAS RELACIONADAS
   BEGIN
      UPDATE PERSONAS_RELACIONADAS
      SET RLC_ESTADO = 'I'
      WHERE RLC_CLI_PER_NUM_IDEN = N_IDEN
        AND RLC_CLI_PER_TID_CODIGO = T_IDEN;               
    EXCEPTION WHEN OTHERS THEN
	     RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE actualizando PERSONAS_RELACIONADAS: '||sqlerrm);
    END;
              
    -- INACTIVACION SEGUNDOS TITULARES
    BEGIN
	     UPDATE OS_CLIENTES
       SET OCL_ESTADO = 'I'
       WHERE OCL_CLI_PER_NUM_IDEN = N_IDEN
         AND OCL_CLI_PER_TID_CODIGO = T_IDEN;
    EXCEPTION WHEN OTHERS THEN
	     RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE actualizando OS_CLIENTES: '||sqlerrm);
    END;
           
    -- INACTIVACION CUENTAS_CORREDORES
    BEGIN
    	  UPDATE CUENTAS_CLIENTE_CORREDORES
   	    SET CCC_CUENTA_ACTIVA = 'N'
    	  WHERE CCC_CLI_PER_NUM_IDEN   = N_IDEN
          AND CCC_CLI_PER_TID_CODIGO = T_IDEN;
    EXCEPTION WHEN OTHERS THEN
	     RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE actualizando CUENTAS_CLIENTE_CORREDORES: '||sqlerrm);
    END;
              
    -- INACTIVACION CUENTAS FONDOS
    BEGIN
      	UPDATE CUENTAS_FONDOS
     	  SET  CFO_ESTADO = 'I'
       	WHERE CFO_CCC_CLI_PER_NUM_IDEN = N_IDEN 
          AND CFO_CCC_CLI_PER_TID_CODIGO = T_IDEN;
    EXCEPTION WHEN OTHERS THEN
	     RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE actualizando CUENTAS_FONDOS: '||sqlerrm);
    END;
            
    -- INACTIVACION CUENTAS BANCARIAS
    BEGIN
       UPDATE CUENTAS_BANCARIAS_CLIENTES
       SET CBC_ESTADO = 'I'
       WHERE CBC_CLI_PER_NUM_IDEN = N_IDEN
         AND CBC_CLI_PER_TID_CODIGO = T_IDEN;
    EXCEPTION WHEN OTHERS THEN
	     RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE actualizando CUENTAS_BANCARIAS_CLIENTES: '||sqlerrm);
    END;
            
    -- INACTIVACION CUENTAS_BANCARIAS EXTERIOR
   BEGIN
      UPDATE  CUENTAS_BANCARIAS_CLIENTES_EXT
      SET CBX_ESTADO = 'I'
      WHERE CBX_CLI_PER_NUM_IDEN   = N_IDEN
        AND CBX_CLI_PER_TID_CODIGO = T_IDEN;             
   EXCEPTION WHEN OTHERS THEN
	    RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE actualizando CUENTAS_BANCARIAS_CLIENTES_EXT: '||sqlerrm);
   END; 
	
    -- INACTIVACION CONTRATOS
   BEGIN
      UPDATE  CONTRATOS
      SET CNT_ESTADO      = 'I'
      WHERE CNT_CLI_PER_NUM_IDEN   = N_IDEN
        AND CNT_CLI_PER_TID_CODIGO = T_IDEN;             
   EXCEPTION WHEN OTHERS THEN
	    RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE actualizando CONTRATOS: '||sqlerrm);
   END; 

   -- VAGTUS014652 - REVISION INACTIVACION PROCESO AUTOMATICO 
   -- SE INACTIVA LA CUENTA DECEVAL DE LA QUE ES COMITENTE Y NO TIENE PORTAFOLIO
   BEGIN
      UPDATE CUENTAS_DECEVAL
      SET CUD_ESTADO = 'I'
      WHERE CUD_ESTADO = 'A'
        AND EXISTS (SELECT 'X'
                    FROM COMITENTES_DECEVAL
                    WHERE COD_CUD_CUENTA_DECEVAL = CUD_CUENTA_DECEVAL
                      AND COD_OCL_CLI_PER_NUM_IDEN = CUD_CLI_PER_NUM_IDEN
                      AND COD_OCL_CLI_PER_TID_CODIGO = CUD_CLI_PER_TID_CODIGO
                      AND COD_CLI_PER_NUM_IDEN_RELACIONA = N_IDEN
                      AND COD_CLI_PER_TID_CODIGO_RELACIO   = T_IDEN);

   EXCEPTION WHEN OTHERS THEN
	    RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE actualizando CUENTAS DECEVAL: '||sqlerrm);
   END;

   -- SE INACTIVA LA CUENTA DECEVAL DE LA QUE ES DUEÑO
   BEGIN
      UPDATE CUENTAS_DECEVAL
      SET CUD_ESTADO = 'I'
      WHERE CUD_ESTADO = 'A'
        AND CUD_CLI_PER_NUM_IDEN = N_IDEN
        AND CUD_CLI_PER_TID_CODIGO = T_IDEN;

   EXCEPTION WHEN OTHERS THEN
	      RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE actualizando CUENTAS DECEVAL: '||sqlerrm);
   END;

   -- SE INACTIVA LA CUENTA DCV DE LA QUE ES COMITENTE - EN ESTA FASE NO SE VALIDA PORTAFOLIO
   BEGIN
      UPDATE CUENTAS_DCV
         SET CDC_ESTADO = 'I'
       WHERE CDC_ESTADO = 'A'
         AND EXISTS (SELECT 'X'
                     FROM  COMITENTES_DCV
                     WHERE CDCV_CDC_CUENTA_DCV = CDC_CUENTA_DCV
                       AND CDCV_OCL_CLI_PER_NUM_IDEN = CDC_CLI_PER_NUM_IDEN
                       AND CDCV_OCL_CLI_PER_TID_CODIGO = CDC_CLI_PER_TID_CODIGO
                       AND CDCV_CLI_PER_NUM_IDEN_RELACI = N_IDEN
                       AND CDCV_CLI_PER_TID_CODIGO_RELACI = T_IDEN);

   EXCEPTION WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE actualizando CUENTAS DCV: '||sqlerrm);
   END;

   -- SE INACTIVA LA CUENTA DECEVAL DE LA QUE ES DUEÑO
   BEGIN
      UPDATE CUENTAS_DCV
      SET CDC_ESTADO = 'I'
      WHERE CDC_ESTADO = 'A'
        AND CDC_CLI_PER_NUM_IDEN = N_IDEN
        AND CDC_CLI_PER_TID_CODIGO = T_IDEN;

   EXCEPTION WHEN OTHERS THEN
	    RAISE_APPLICATION_ERROR(-20003,'Error en procedimiento INACTIVA_CLIENTE actualizando CUENTAS DCV: '||sqlerrm);
   END;
   -- FIN - VAGTUS014652 - REVISION INACTIVACION PROCESO AUTOMATICO
   

END INACTIVA_CLIENTE;                            


END;

/
